# Generated by Django 5.2.7 on 2025-11-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='avatar URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('SERVIDOR', 'Servidor'), ('ALUNO', 'Aluno')], max_length=20, null=True, verbose_name='tipo'),
        ),
    ]
