# Generated by Django 5.2.7 on 2025-11-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar_url_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_suap_user',
            field=models.BooleanField(default=False, help_text='Indica se o usuário foi criado via login SUAP', verbose_name='usuário SUAP'),
        ),
    ]
