# Generated by Django 5.2.7 on 2025-11-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_suap_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_suap_user',
            field=models.BooleanField(default=False, help_text='Indica se o usuário foi criado via login SUAP', verbose_name='Usuário SUAP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('SERVIDOR', 'Servidor'), ('ALUNO', 'Aluno')], max_length=20, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome de usuário'),
        ),
    ]
