# Generated by Django 5.2.7 on 2025-11-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_avatar_url_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, help_text='Nome completo do usuário (usa nome social se disponível)', max_length=255, null=True, verbose_name='Nome completo'),
        ),
    ]
