# Generated by Django 5.2.7 on 2025-11-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curso',
            field=models.CharField(blank=True, help_text='Curso do aluno (apenas para tipo ALUNO)', max_length=255, null=True, verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='user',
            name='periodo_referencia',
            field=models.CharField(blank=True, help_text='Período de referência do aluno (apenas para tipo ALUNO)', max_length=50, null=True, verbose_name='Período de Referência'),
        ),
    ]
