# Generated by Django 5.2.7 on 2025-11-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_curso_user_periodo_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campus',
            field=models.CharField(blank=True, help_text='Campus do usuário no IFRN', max_length=255, null=True, verbose_name='Campus'),
        ),
    ]
