# Generated by Django 5.2.7 on 2025-11-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='periodo_referencia',
            field=models.CharField(blank=True, help_text='Período de referência do aluno (apenas para tipo ALUNO)', max_length=50, null=True, verbose_name='Período'),
        ),
    ]
