# Generated by Django 5.2.7 on 2025-12-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name_normalized',
            field=models.CharField(blank=True, db_index=True, help_text='Nome sem acentos para ordenação', max_length=255, null=True, verbose_name='Nome normalizado'),
        ),
    ]
