# Generated by Django 5.2.7 on 2025-12-04 04:56

from django.db import migrations
import unicodedata


def populate_normalized_names(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        if user.full_name:
            # NFD = Canonical Decomposition (separates base chars from accents)
            nfd = unicodedata.normalize('NFD', user.full_name)
            # Filter out combining characters (accents) and convert to uppercase
            user.full_name_normalized = ''.join(
                char for char in nfd
                if unicodedata.category(char) != 'Mn'
            ).upper()
            user.save(update_fields=['full_name_normalized'])


def reverse_populate(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.update(full_name_normalized=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_full_name_normalized'),
    ]

    operations = [
        migrations.RunPython(populate_normalized_names, reverse_populate),
    ]
