services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped

  web:
    image: ghcr.io/ifrn-spp/presente:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${SERVER_STATIC_ROOT}:/app/staticfiles
      - ${SERVER_MEDIA_ROOT}:/app/media
      - ${SOCKET_DIR}:/run/sockets
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
