# Generated by Django 5.2.7 on 2025-11-26 22:11

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0003_activity_owner_event_owner'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Tags para organizar as atividades (ex: 'Workshop 2024', 'Python')",
                through='taggit.TaggedItem',
                to='taggit.Tag',
                verbose_name='tags'
            ),
        ),
    ]
