# Generated by Django 5.2.7 on 2025-11-27 02:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0006_remove_event_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='owner',
        ),
        migrations.AddField(
            model_name='activity',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owned_activities', to=settings.AUTH_USER_MODEL, verbose_name='owners'),
        ),
    ]
