# Generated by Django 5.2.7 on 2025-11-27 21:39

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0007_remove_activity_owner_activity_owners'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.DateTimeField(verbose_name='Data/hora de término'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Define se a atividade está visível para registro de presença', verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owned_activities', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='qr_timeout',
            field=models.IntegerField(default=30, help_text='Tempo de validade de cada QR Code para registro de presença (em segundos)', verbose_name='Timeout do QR Code (segundos)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.DateTimeField(verbose_name='Data/hora de início'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text="Tags para organizar as atividades (ex: 'Workshop 2024', 'Python')", through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='presente.activity', verbose_name='Atividade'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='checked_in_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registrado em'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
