# Generated by Django 5.2.7 on 2025-11-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0008_alter_activity_end_time_alter_activity_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='allowed_networks',
            field=models.TextField(blank=True, help_text='IPs ou redes permitidas (um por linha). Exemplo: 192.168.1.0/24 ou 10.0.0.1', null=True, verbose_name='Redes permitidas'),
        ),
        migrations.AddField(
            model_name='activity',
            name='restrict_ip',
            field=models.BooleanField(default=False, help_text='Ativar restrição de acesso por endereço IP', verbose_name='Restringir por IP'),
        ),
    ]
