# Generated by Django 5.2.7 on 2025-11-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0009_activity_allowed_networks_activity_restrict_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nome identificador da rede (ex: 'Campus Natal Central')", max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, help_text='Descrição opcional da rede', verbose_name='Descrição')),
                ('ip_addresses', models.TextField(help_text='IPs ou redes permitidas (um por linha). Exemplo: 192.168.1.0/24 ou 10.0.0.1', verbose_name='Endereços IP/Redes')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque para desativar temporariamente esta rede', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Rede',
                'verbose_name_plural': 'Redes',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='activity',
            name='allowed_networks',
        ),
        migrations.AddField(
            model_name='activity',
            name='allowed_networks',
            field=models.ManyToManyField(blank=True, help_text='Selecione as redes que podem acessar esta atividade', to='presente.network', verbose_name='Redes permitidas'),
        ),
    ]
