# Generated by Django 5.2.7 on 2025-11-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0010_network_remove_activity_allowed_networks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Endereço IP do usuário no momento do check-in', null=True, verbose_name='Endereço IP'),
        ),
    ]
