# Generated by Django 5.2.7 on 2025-11-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0011_add_ip_address_to_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='is_published',
        ),
    ]
