# Generated by Django 5.2.7 on 2025-11-29 23:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0012_remove_is_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Habilitar?'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='owners',
            field=models.ManyToManyField(related_name='owned_activities', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='qr_timeout',
            field=models.IntegerField(default=0, help_text='Tempo de validade de cada QR Code para registro de presença (em segundos). Use "0" para desabilitar.', verbose_name='Timeout do QR Code (segundos)'),
        ),
    ]
