# Generated by Django 5.2.7 on 2025-11-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0013_activity_is_enabled_alter_activity_owners_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Habilitar o registro de presença.', verbose_name='Habilitar?'),
        ),
    ]
