# Generated by Django 5.2.7 on 2025-12-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0014_alter_activity_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='activity',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado em'),
        ),
    ]
