# Generated by Django 5.2.7 on 2025-12-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0015_activity_created_at_activity_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criação'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.DateTimeField(verbose_name='Término'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modificação'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.DateTimeField(verbose_name='Início'),
        ),
    ]
